CAST(CASE reporting_period
WHEN Extract('month' from CAST(reporting_period AS DATE)) = 1 THEN CAST('2020-01-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 2 THEN CAST('2020-02-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 3 THEN CAST('2020-03-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 4 THEN CAST('2020-04-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 5 THEN CAST('2020-05-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 6 THEN CAST('2020-06-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 7 THEN CAST('2020-07-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 8 THEN CAST('2020-08-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 9 THEN CAST('2020-09-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 10 THEN CAST('2020-10-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 11 THEN CAST('2020-11-01' AS DATE)
ELSE (CASE WHEN Extract('month' from CAST(reporting_period AS DATE)) = 12 THEN CAST('2020-12-01' AS DATE)
ELSE NULL END)END)END)END)END)END)END)END)END)END)END)END AS TEXT)